### ISSUE TITLE
Faq needs updating

### ISSUE THREAD

**Issue by Computerfan23** [zeldaret/tmc#655]
Hi there!
I was reading the faq for tmc on the website and there is a section called pc port. In this section, the text mentions pokemon emerald but there does not exist any pc port for that game.
So i would suggest editing the text to remove that bit about pokemon emerald since it could be misleading.

**Comment by LOuroboros** [comment]
> but there does not exist any pc port for that game.

That is incorrect, [there is one](https://github.com/Kurausukun/pokeemerald/tree/pc_port).

**Comment by Computerfan23** [comment]
Hi!
I was not aware of that. I thought there was no pokemon emerald port
